# Generated by Django 5.2.4 on 2025-07-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='color_selection',
            field=models.CharField(default='#FF5733', max_length=7),
        ),
    ]
